version: '3'
services:
  airflow-worker:
    volumes:
      - ./dbt_project:/opt/airflow/dbt_project/dbt_project
    build:
      context: .
      dockerfile: Dockerfile
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
